In [2]:
import numpy as np


In [4]:
data = np.array([[26,50000],[29,70000],[34,55000],[31,40000]])

In [5]:
data

array([[   26, 50000],
       [   29, 70000],
       [   34, 55000],
       [   31, 40000]])

__NORMALIZATION__




In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaled_data =scaler.fit_transform(data)
scaled_data


array([[0.        , 0.33333333],
       [0.375     , 1.        ],
       [1.        , 0.5       ],
       [0.625     , 0.        ]])

__STANDERDIZATION__

In [8]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
scaled_data = scaler.fit_transform(data)
scaled_data

array([[-1.37198868, -0.34641016],
       [-0.34299717,  1.5011107 ],
       [ 1.37198868,  0.11547005],
       [ 0.34299717, -1.27017059]])